package TODO;

public class CustomEvents {
    //Variables
    private String name;
    private String location;
    //Using ClassTime[] since I'm not sure how else to store the time
    private ClassTime[] times;

    //Constructor, generated by GitHub Copilot
    public CustomEvents(String name, String location, ClassTime[] times) {
        this.name = name;
        this.location = location;
        this.times = times;
    }

    // Getters, generated by GitHub Copilot
    public String getName() {
        return name;
    }

    public String getLocation() {
        return location;
    }

    public ClassTime[] getTimes() {
        return times;
    }

    // Setters, generated by GitHub Copilot
    public void setName(String name) {
        this.name = name;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setTimes(ClassTime[] times) {
        this.times = times;
    }

}
